n_epochs: 100
resume_epoch: ~
n_train_steps_per_epoch: ~
n_eval_steps_per_epoch: ~
dataset_name: img_align_celeba
batch_size: 32
lr: 0.0002
b1: 0.5
b2: 0.999
n_cpu: 8
decay_epoch: 100
hr_height: 256
hr_width: 256
channels: 3
sample_interval: 100
checkpoint_interval: 10
path:
  writer: ./runs
  data: ../data
  models: ./saved_models
  training_state: ./states
  images: ./images

